# Generated by Django 2.2.9 on 2022-11-24 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20221124_0753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='decsription',
            new_name='description',
        ),
    ]
