# Generated by Django 2.2.9 on 2022-11-25 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20221125_0633'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'default_related_name': '%(app_label)s_%(model_name)s', 'ordering': ['-pub_date']},
        ),
    ]
