# Generated by Django 2.2.16 on 2022-12-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20221220_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(help_text='Введите текст поста', max_length=15, verbose_name='Текст поста'),
        ),
    ]
